### ISSUE TITLE
Searching for a usable .js / .min.js file?

### ISSUE THREAD

**Issue by pwFoo** [egoist/franxx#3]
Searching for a file to use with script tag?

**Comment by egoist** [comment]
https://unpkg.com/franxx@0.1.2/dist/ as `window.franxx`

**Comment by pwFoo** [comment]
Copied code and loaded by script tag, but can't use it 
```
        var router = new HistoryRouter();
```
or
```
        import { HistoryRouter, HashRouter, MemoryRouter } from 'franxx';
        var router = new HistoryRouter();
```

Error messages:
```
Uncaught ReferenceError: HistoryRouter is not defined
```

```
Uncaught SyntaxError: Unexpected token {
```

How to use the min.js just with plain JS?

**Comment by pwFoo** [comment]
Also tried many import commands inside of script tag and script tag with type module...
Haven't found a working solution to use franxx :(

```
Uncaught ReferenceError: HistoryRouter is not defined
```

**Comment by pwFoo** [comment]
```
Uncaught SyntaxError: The requested module './franxx.js' does not provide an export named 'default'
```

**Comment by pwFoo** [comment]
Not able to import it... give up...

**Comment by egoist** [comment]
`franxx.HistoryRouter` should work

**Comment by pwFoo** [comment]
Thanks, now it loaded successful as (normal) script and used with `franxx.HistoryRouter`.

**Comment by BenitoJedai** [comment]
Hi How i can use the last version 1.2.1 of FRANXX ROUTER in Browser Directly and how fix 404 error when input url from adress bar supose apache server

**Comment by BenitoJedai** [comment]
Please help me i consider using this router because is very good for me i need like this
<script src="franxx.min.js"></script>
<script>
const router= new createBrowserHistory()

// go code here

</script>

**Comment by egoist** [comment]
@BenitoJedai I added a section about CDN usage: https://github.com/egoist/franxx/blob/master/README.md#cdn

For Apache, you can use rewrite rules like this: https://gist.github.com/santthosh/7dabf08fa3859361ef1e

**Comment by BenitoJedai** [comment]
@egoist hi mmm not work!! Try from your browser here the code in https://pitogue.ewmania.com and view source not work any

**Comment by BenitoJedai** [comment]
You can build only franxx bundler with all dependency inside like history regexparam and /dist/franxx.min.js only all people use only this js file in browser directly

**Comment by BenitoJedai** [comment]
Not work for me what are the problem 😷😓😣😯

**Comment by BenitoJedai** [comment]
Hey Man please helpme i need this i test with jsdelivr but not work!!! 😓😐🤐😣

**Comment by BenitoJedai** [comment]
Franxx is no defined

**Comment by BenitoJedai** [comment]
After edit and edit and edit and no work errors and errors production not defined and other errors

**Comment by BenitoJedai** [comment]
Please Build bundle final release of franxx for browser ready with all dependency inside for usage with cdn or download franxx.min.js locally usage

**Comment by BenitoJedai** [comment]
Thanks i waiting for you fix ☺
